### PR TITLE
PnMPI 1.7

### PR DESCRIPTION
**Pull request by alehaa**
May I introduce? This is PnMPI v1.7!

PnMPI v1.7 has some nice new features, three new modules, a coding convention was introduced, lots of documentation and feature tests were added, several bugs fixed and required submodules have been updated if necessary. Below I'll explain this pull request in detail.

*Please get yourself a fresh coffee - this pull request will need some time. ;)*

## New features

* A bunch of new test cases for the PnMPI core and the module API was added. These test cases use our [CMake-easytest](https://github.com/RWTH-HPC/CMake-easytest) script for easy test definitions and -handling. The whole PnMPI code (including test cases and modules) can be checked by [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer), [UndefinedBehaviourSanitizer](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) and code coverage *(not at all platforms / with all compilers)*.

* [Travis CI](https://travis-ci.org/LLNL/PnMPI) continuous integration was added in combination with [codecov.io](https://codecov.io/gh/LLNL/PnMPI) to check the build of PnMPI and its test cases. Ubuntu 12.04 and 14.04 (both with OpenMPI) and several mac OS XCode versions will be covered (OpenMPI + MPICH), gcc builds in combination with sanitizers and code coverage. Additional tests for the coding convention, license header, optimized build, build without Fortran and deploy are included, too.
  * As `git archive` does not include submodules to the packed archive, packaging will be done by a small wrapper in `extra/pack.sh`, which itself uses [git-archive-all](https://github.com/Kentzo/git-archive-all). The Travis CI build may be enhanced to upload the packed tarball to github on any tags build, which will be attached to the tag at the [relases](https://github.com/LLNL/PnMPI/releases) page. The following config can be used, but a valid upload token will be required.

    ```yaml
    before_deploy:
      - cd $PWD_SAVE
      - export DEPLOY_FILE=$(find $PWD/package/*.tar.gz)
      - echo "Deploying $DEPLOY_FILE"
    deploy:
      provider: releases
      api_key:
        secure: |-
          W3Tx+8mgX/rSJYxvxBylDGh0h8/gM+MKHdCI7DGD0PltDRDF/M8m6ApjBA3f6pAmTvBR
          GXWAgKNp0jENcOgsdgrfGHV1OnhFVxHr1i2gU+HyEsaawebM5N7+LJUxaHLJVTjM4+8f
          XLvpHVrToKRY6St4N7l7+bJAr+VHZaI3$
      file: "$DEPLOY_FILE"
      skip_cleanup: true
      on:
        tags: true
        repo: LLNL/PnMPI
    ```
    In addition, the script may also be used to  to pack individual releases which are non-tagged.

* A new binary named `pnmpi` was introduced to configure and preload the PnMPI environment for dynamic linked MPI executables. There is no need for configure PnMPI via environment variables anymore, but this tool is fully compatible to the environment variable solution.

* ~~Two new hooks have been introduced: `PNMPI_AppStartup` and `PNMPI_AppShutdown`, which will be run before and after `main`. If the startup hook is enabled, MPI will be initialized *before* main is started and if shutdown is enabled, MPI won't be finalized until all of these hooks have finished, even if the application did call `MPI_Finalize` this will only be passed to the tools but not to `PMPI_Finalize`. This allows the tool to use MPI after the application called `MPI_Finalize`.~~
  
  ~~*If the platform can't handle con- and destructors, these hooks will be called in the `MPI_Init` / `MPI_Finalize` wrappers, but before / after all other modules have been executed.*~~

  ~~In addition each module can call custom hooks of following modules in the same or different stacks by using the new `PNMPI_Service_CallHook()` and `_NewStack()` functions.~~

* Three new hooks have been introduced: `PNMPI_Init`, `PNMPI_Fini` and `PNMPI_UnregistrationPoint ` will be called for module initialization after registration, de-initialization just before unregistration and for unregistration. Modules should include the new header `<pnmpi/hooks.h>` for type safety, if they define any hooks.

* `MPI_Init_thread` will be handled now. ~~Modules are able to tell PnMPI via the `PNMPI_SupportedThreadingLevel` symbol, if they are not thread safe. PnMPI will then limit the threading level required in `MPI_Init_thread` automatically.~~

* The module service functions have been reworked: They have been splitted into a bunch of files. Also some functions got a short-hand-function to get specific data for the calling module to save implementation work for first querying the Module ID before querying the data. Each function got a detailed coumentation with Doxygen and man-pages will be generated from these docs. There is even a new symbol `PNMPI_ModuleName` modules may define to simply register their name. Services use the new header `<pnmpi/service.h>` now, but compatibility for `pnmpimod.h` is ensured.

* A set of debug printing functions was added to PnMPI's API for printing debug informations, warnings and errors inside PnMPI or modules. Debug output may be dynamically enabled by environment variables or the PnMPI invocation tool now. PnMPI doesn't need to be recompiled for this feature, but for performance gain, this feature may also be disabled entirely.

* Timing-statistics and MPI call counters have been sourced out into two standalone modules `metrics-timing` and `metrics-counter`. These features don't need to be enabled and disabled by compile options anymore, but can be enabled on demand by loading the specific module. See the README for a detailed description on using these modules.

* The new module `wait-for-debugger` may be used to stop the applications execution before running - enough time to attach to a specific rank with a debugger.

* PnMPI does not need pthreads (introduced in `v1.6`) for the thread-local-storage anymore. If available, C11 `__thread` or compiler specific implementations will be used. If thread-local-storage is unavailable, PnMPI will automatically limit the MPI threading level required in `MPI_Init_thread`. For performance gain, this feature may also be disabled entirely.

* A fallback for the PnMPI initialization has been implemented: If the compiler doesn't understand `__attribute__((constructor))` and the linker can't handle `_init`, PnMPI initialization will take place in `MPI_Init`, just as before introducing thread safety in `v1.6`.

* Instead of maintaining PnMPI's version number in the root `CMakeLists.txt` file, this will be done by [CMake-gitinfo](https://github.com/RWTH-HPC/CMake-gitinfo) now. The output of `git describe --tags` will be used as version string now and is similar to `v1.6-227-geacc049` which is equivalent to version `1.6.227` (major, minor, patch). A version file for non-git deploys (e.g. as tarball) will be included by the `extra/pack.sh` script automatically.

* [Generic MPI feature tests](https://github.com/RWTH-HPC/CMake-MPIhelper) will be used now to reduce the maintenance overhead.

* Based on the current coding style of `v1.6`, a clang-format configuration file was generated. Travis CI will check that *all* commits of a branch follow this convention and will fail if any commit does not. This will ensure that pull requests don't send 90% of "changed two spaces to 4 spaces". *The current configuration is compatible with clang-format 3.8, but may have to be adjusted for future releases for clang-format.*

## Bugfixes

* Several fixes in combination with [wrap](https://github.com/LLNL/wrap). Most of it was done in the wrap, the PnMPI code was fixed to work with newer versions of wrap. Wrap should be compatible with python 3 now.
* Several memory leaks have been fixed in the PnMPI core and patch utility.
* In addition to enhancing the README file, the markdown code was cleaned up and broken markup fixed. Badges for Travis CI build status, code coverage, GitHub issues and the license have been added.
* Fixes for #4 and #5.
* Fixed con- and destructors in combination with static linking.

## misc

* Re-organized the source tree.
* Ran a beautifier over the whole code to enforce the coding convention.
* Unused code was deleted, especially remains from wrap before it was a submodule. *(Exception: `request.c` of PnMPI remained in favor of @jprotze. If anybody knows about the purpose of this file, I'll add it to the new module service function interface.)*
* Code for unsupported or deprecated platforms (Windows and AIX) was removed.
* The license header has been updated to a full LGPL license header with the current dates and contributers. A LICENSE file was added.
* PnMPI got a new banner at the console with nice ASCII art logo.
* Bumped minimum required CMake version to `2.8.11.2`.

----

*Please note: As the current master of this repository doesn't fit the license-header- and coding-convention-requirements, Travis CI will show a build-failure, as these checks will be done on the diff between the master and this pull request.*

### CODE REVIEW

**Comment by alehaa** [comment]
@tgamblin, @jprotze: Would be nice if you could check this at a BlueGene, as I don't have access to one. I did check this PR at our cluster (Linux x86_64) and mac OS, Travis checks run at Ubuntu 12.04 / 14.04 and mac OS.

**Comment by alehaa** [comment]
Unfortunately the new introduced hooks didn't work well with other applications like GTI. They have been reworked and behave like the wrapped MPI calls now: modules decide where to recurse into the next module, now. In addition a module may call custom hooks now by calling `PNMPI_Service_CallHook()` with a custom hook name.

Minor bugfixes and enhancements in the `README` have been committed.

**Comment by kento** [comment]
Hi @alehaa, 

So fare, I get this error in cmake. Could you fix this ? or, am I building new PnMPI wrongly ?

CMake Error at CMakeLists.txt:105 (find_package):
  By not providing "FindGitInfo.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "GitInfo", but
  CMake did not find one.

  Could not find a package configuration file provided by "GitInfo" with any
  of the following names:

    GitInfoConfig.cmake
    gitinfo-config.cmake

  Add the installation prefix of "GitInfo" to CMAKE_PREFIX_PATH or set
  "GitInfo_DIR" to a directory containing one of the above files.  If
  "GitInfo" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by alehaa** [comment]
`git submodule update --init --recursive` should fix this. A paragraph was added to README.md, but not merged into this PR yet.

**Comment by kento** [comment]
OK, thanks !

**Comment by alehaa** [comment]
After some discussion with @jprotze we've removed the *AppHooks* feature, as it doesn't follow the PnMPI standard way of hooking into MPI applications (as it started the MPI environment before the application called `MPI_Init`). The entire code has been tested on mac OS, Ubuntu 12.04 and 14.04, the RWTH cluster (CentOS) and on LLNL's vulcan, so I think it's ready to be merged, if @tgamblin and @schulzm don't have any concerns?

I've one last question about the code: New code I wrote follows C99 standard (I mixed up declarations and code and used VLAs). Most compilers work with these features without explicit enabling C99. However, I'll have to add C99 flags for compiling with several warning-flags enabled. I wonder if we shouldn't set `find_package(C99)` to `REQUIRED` instead of *optional*. What do you think about this @tgamblin & @jprotze?

**Pull request merged**
