### PR TITLE
CORAL EA Porting & Bug fix

### PR DESCRIPTION
**Pull request by kento**

### CODE REVIEW

**Comment by alehaa** [comment]
Hi @kento, currently we're finishing PR #6 which will include some of your patches. I think it will be better to merge #6 first, then merging patches from this PR if not already merged by #6.

**Comment by alehaa** [comment]
@kento I've integrated your changes into our fork for rc3 of #6. Thanks for contributing!

**Comment by kento** [comment]
OK, thanks !

**Comment by alehaa** [comment]
@kento The compiler complains about `#if BFD_SUPPORTS_PLUGINS==0`, as there are extra tokens after at the end of the expression (`==0`). I tried to fix it, but as I don't know what was the intention of this macro, my code crashes ...

Can you tell me what conditions this macro should check, so I can fix this?

**Comment by kento** [comment]
@alehaa Depending on BFD version, a structure of bfd defined in <bfd.h> is different. 
But, BFD does not have macro like BFD_VERSION.
Instead, I used BFD_SUPPORTS_PLUGINS to detect the version in order to switch between ->link_next and ->link.next.

**Comment by jprotze** [comment]
The compiler complained about `#ifdef BFD_SUPPORTS_PLUGINS==0` should it be 
`#if defined(BFD_SUPPORTS_PLUGINS) && BFD_SUPPORTS_PLUGINS==0` ?

Or `#if !defined(BFD_SUPPORTS_PLUGINS) || BFD_SUPPORTS_PLUGINS==0` ?

**Comment by alehaa** [comment]
@jprotze Both of your suggestions end in compiler errors. That's why I need the translation of the macro by @kento ;) 

```
Scanning dependencies of target pnmpi-patch
[  0%] Building C object src/patch/CMakeFiles/pnmpi-patch.dir/patch.c.o
.../src/patch/patch.c: In function 'copy_archive':
.../src/patch/patch.c:945:28: error: 'bfd' has no member named 'next'
           ptr = &output_bfd->next;
                            ^
```

**Comment by kento** [comment]
It seems we need to properly switch among:

1. ptr = &output_bfd->archive_next
2. ptr = &output_bfd->next
3. ptr = &output_bfd->link_next;
4. ptr = &output_bfd->link.next;

**Pull request closed without merging**
